name: Python package

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["workflow2"]  # testing

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.14"]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install pipenv and build
        run: |
          python -m pip install --upgrade pip
          python -m pip install pipenv build

      - name: Install dependencies
        run: pipenv install --dev

      - name: Run tests
        run: PYTHONPATH=. pipenv run pytest

      - name: Build package
        run: pipenv run python -m build